name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Use npm
        run: npm install
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
